apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: 
    app: go-web-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: go-web-app
  type: ClusterIP  
